#!env perl

use Schedule::Cron;
use Getopt::Std;
use POSIX;

main();

sub main{
    get_opts();
    %CFG = read_cfg();
    
    my $c = new Schedule::Cron(\&dispatcher); 

    return 0;
}

sub dispatcher {
    my ( $id, @args ) = @_;

    # nice the process
    POSIX::nice($DNICE);
}

sub read_config {
	# processname, niceness
    open my $fh, '<', $CONFIG or die "Cannot open $CONFIG: $";
	while ( my $line = <$fh> ) {
		chomp;
		my
	}
	close $fh;

}

sub get_opts {
	my %o = ();
    getopts('C:F:N:',\%o);

    $CRONFILE = $o{F} ? $o{F} : undef;
    $CONFIG = $o{C} ? $o{C} : undef;
    $DNICE = $o{N} ? $o{N} : 10;
}
